dataset:
  abnormal_dir: colour
  eval_batch_size: 2
  extensions: null
  format: folder
  image_size:
  - 512
  - 512
  mask_dir: mask
  name: Paper
  normal_dir: good
  normal_test_dir: null
  normalization: imagenet
  num_workers: 8
  root: C:\Users\asad3\Documents\xis\usaisoft-platform-backend\Datasets\anomalib_data_1697775137_06864c11
  seed: 0
  split_ratio: 0.2
  task: segmentation
  test_split_mode: from_dir
  test_split_ratio: 0.2
  tiling:
    apply: false
    random_tile_count: 16
    remove_border_count: 0
    stride: null
    tile_size: null
    use_random_tiling: false
  train_batch_size: 2
  transform_config:
    eval: null
    train: null
  val_split_mode: from_test
  val_split_ratio: 0.5
logging:
  log_graph: false
  logger: []
metrics:
  image:
  - AUROC
  pixel:
  - AUROC
  threshold:
    adaptive: true
    image_default: null
    manual_image: null
    manual_pixel: null
    method: adaptive
    pixel_default: null
model:
  amsgrad: true
  backbone: resnet18
  early_stopping:
    metric: pixel_AUROC
    mode: max
    patience: 5
  gamma_c: 1
  gamma_d: 1
  input_size:
  - 512
  - 512
  lr: 0.001
  name: cfa
  normalization_method: min_max
  num_hard_negative_features: 3
  num_nearest_neighbors: 3
  radius: 1.0e-05
  weight_decay: 0.0005
optimization:
  export_mode: torch
project:
  path: results\cfa\Paper\run
  seed: 0
  unique_dir: false
trainer:
  accelerator: auto
  accumulate_grad_batches: 1
  auto_lr_find: false
  auto_scale_batch_size: false
  benchmark: false
  check_val_every_n_epoch: 1
  default_root_dir: results\cfa\Paper\run
  detect_anomaly: false
  deterministic: false
  devices: 1
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  fast_dev_run: false
  gradient_clip_algorithm: norm
  gradient_clip_val: 0
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  max_epochs: 10
  max_steps: -1
  max_time: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  profiler: null
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  strategy: null
  sync_batchnorm: false
  track_grad_norm: -1
  val_check_interval: 1.0
visualization:
  image_save_path: null
  log_images: true
  mode: full
  save_images: true
  show_images: false
